name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize build environment
        env: 
          CMAKE_C_COMPILER: g++
          CMAKE_CXX_COMPILER: g++
        run: |
          sudo apt install -y cmake libboost-all-dev libhdf5-dev libopenmpi-dev doxygen graphviz python3
          python -m pip install numpy h5py
      - name: Build
        run: |
          mkdir install && cmake -B ${{ github.workspace }}/build -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
          cmake --build ${{github.workspace}}/build --parallel 4
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --verbose
      - name: Install
        run: cmake --install ${{github.workspace}}/build
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/install/doc
          publish_branch: gh-pages