name: Build and test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize build environment
        env: 
          CMAKE_C_COMPILER: g++
          CMAKE_CXX_COMPILER: g++
        run: |
          sudo apt-get update && sudo apt-get install -y cmake libboost-all-dev libhdf5-dev libopenmpi-dev doxygen graphviz python3
          python -m pip install numpy h5py pdoc3 matplotlib
      - name: Build
        run: |
          mkdir install && cmake -B ${{ github.workspace }}/build -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
          cmake --build ${{github.workspace}}/build --parallel 4
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --verbose